base_path: /

routes:
  index: [/, MoS\LAN\Controller\Controllers\PageController.index, GET]
  display_user: [/user, MoS\LAN\Controller\Controllers\PageController.user, GET]
  get_user: [/users, MoS\LAN\Controller\Controllers\UserController.get, GET]
  create_user: [/users, MoS\LAN\Controller\Controllers\UserController.create, POST]
  delete_user: [/users, MoS\LAN\Controller\Controllers\UserController.delete, DELETE]
  update_user: [/users, MoS\LAN\Controller\Controllers\UserController.update, PUT]