base_path: /

routes:
  index: [/, MoS\LAN\Controller\PageController.index, GET]
  user_page: [/user, MoS\LAN\Controller\PageController.user, GET]
  
  get_user: [/users, MoS\LAN\Controller\UserController.get, GET]
  create_user: [/users, MoS\LAN\Controller\UserController.create, POST]
  delete_user: [/users, MoS\LAN\Controller\UserController.delete, DELETE]
  update_user: [/users, MoS\LAN\Controller\UserController.update, PUT]