base_path: /

routes:
  page_index: [/, MoS\LAN\Controller\PageController.index, GET]
  page_user: [/user, MoS\LAN\Controller\PageController.user, GET]
  page_user_id: [/user/:id, MoS\LAN\Controller\PageController.user, GET]
  
  user_get: [/users/:id, MoS\LAN\Controller\UserController.get, GET]
  user_create: [/users/:id, MoS\LAN\Controller\UserController.post, POST]
  user_delete: [/users/:id, MoS\LAN\Controller\UserController.delete, DELETE]
  user_update: [/users/:id, MoS\LAN\Controller\UserController.put, PUT]
  
  error: [/error/:code, MoS\LAN\Controller\ErrorController.error, GET]